[tools]
bun = "latest"
git-cliff = "latest"
lefthook = "latest"
"prettier" = "latest"

[deps.lefthook]
description = "Install lefthook hooks"
run = "lefthook install"
sources = ["lefthook.yml", ".lefthook", ".lefthook-local"]

[settings]
npm.package_manager = "bun"
